[project]
name = "carga-magento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=40.1.0",
    "requests>=2.32.5",
]
